# Site
name: "DogGoDaek"
title: "DogGoDaek"
description: "Discovering the best bites in the animal kingdom"
logo: "assets/images/icon.png"
favicon: "assets/images/icon.png"
baseurl: /doggodaek
google_analytics: "UA-46278016-1"
disqus: "demowebsite"
mailchimp-list: "https://gmail.us18.list-manage.com/subscribe/post?u=9e32a0e6c6ea0c32b9161b852&amp;id=df85997256&amp;f_id=00c725e7f0"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  doggodaek:
    name: DogGoDaek
    display_name: DogGoDaek
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    icon: assets/images/icon.png
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "As a food-loving dog and fox, we have always had a passion for trying new and exciting flavors. Whether you're a seasoned foodie or just looking for some inspiration for your next meal, we hope our reviews will help guide you on your own culinary journey."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
